### ISSUE TITLE
Line in readme goes through image

### ISSUE THREAD

**Issue by arthurvr** [stve/awesome-dropwizard#1]
![stve_awesome-dropwizard](https://cloud.githubusercontent.com/assets/6025224/8679470/1c65ff44-2a5b-11e5-871b-0e04882afd53.png)

I wonder if there's a way we can fix this. Doesn't look right though.

**Comment by stve** [comment]
that bothered me too. I couldn't figure out how to prevent the line so I just shrunk the logo. Cheers!
